repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 41.132.5
    hooks:
      - id: renovate-config-validator

  - repo: local
    hooks:
      - id: prettier
        name: Prettify Code
        entry: npx prettier --write
        language: system
        exclude: "^templates/.*"
