name: Test Latest Release Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Get latest release of Typst
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: typst/typst

      - uses: ./
        with:
          typst_ref: ${{ steps.get-latest-release.outputs.release }}
          retention_days: 7
          artifacts_name: typst_output
          output_extensions: pdf
